# Generated by Django 2.2.1 on 2019-05-25 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='librarian',
            options={'permissions': [('catalog.can_mark_returned', 'Can operate in the library')]},
        ),
    ]
