# Generated by Django 2.2.1 on 2019-05-25 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20190525_1108'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='librarian',
            options={},
        ),
    ]
